
apiVersion: v1
kind: Service
metadata:
  name: event-planner-service
spec:
  selector:
    app: event-planner
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
      protocol: TCP